"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wjsc@uh55fwmyvk3&m)b-%g_k6thdks=-)gdo7blro0+2+cnuo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False 

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# After a successful login, redirect the user to the home page ('/')
LOGIN_REDIRECT_URL = '/'

AUTH_USER_MODEL = 'bookshelf.CustomUser'

SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY' # Prevents your site from being put in an iframe (clickjacking)
SECURE_CONTENT_TYPE_NOSNIFF = True

# 4. Enforce HTTPS for cookies in production
#    These settings tell the browser to only send cookies over a secure HTTPS connection.
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

CSP_DEFAULT_SRC = ("'self'",)


if not DEBUG:
    
    # 1. Enforce HTTPS
    # Tells Django to redirect all non-HTTPS (HTTP) requests to HTTPS.
    SECURE_SSL_REDIRECT = True
    
    # 2. Configure HTTP Strict Transport Security (HSTS)
    # Tells the browser to only communicate with the site over HTTPS for a year.
    SECURE_HSTS_SECONDS = 31536000  # 365 * 24 * 60 * 60 = 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True # Apply HSTS to all subdomains as well.
    SECURE_HSTS_PRELOAD = True # Allows your site to be submitted to browser preload lists.
    
    # 3. Enforce Secure Cookies
    # Ensures that session cookies are only sent over secure (HTTPS) connections.
    SESSION_COOKIE_SECURE = True
    
    # Ensures that the CSRF cookie is only sent over secure (HTTPS) connections.
    CSRF_COOKIE_SECURE = True

# --- General Security Headers (Good for both development and production) ---

# 4. Prevent Clickjacking
# Instructs the browser not to allow your site to be rendered in an <iframe>.
X_FRAME_OPTIONS = 'DENY'

# 5. Prevent MIME-Type Sniffing
# Stops the browser from trying to guess a file's type, forcing it to
# respect the Content-Type header from the server.
SECURE_CONTENT_TYPE_NOSNIFF = True

# 6. Enable Browser XSS Filter
# NOTE: This is an older setting and modern browsers have largely replaced its
# functionality with Content Security Policy (CSP). However, it is required by the task
# and provides protection for users on older browsers.
SECURE_BROWSER_XSS_FILTER = True